source "http://rubygems.org"

gem 'daemon-kit', :git => "git@github.com:kitplummer/daemon-kit.git"
gem 'safely'
gem 'ruote' 
gem 'ruote-stomp', :git => "git@github.com:maestrodev/ruote-stomp.git"
gem 'rspec'
gem 'eventmachine'
gem 'json'
gem 'yajl-ruby'

gem 'stompserver'
