# Sample configuration file for a remote participant daemon

# If your using the AMQP listener/participant pair in ruote, you only
# need to specify the names of the queues to subscribe to.

defaults: &defaults
  amqp:
    queues:
      - pong
      #- work2
      #- work3
  stomp:
      queues:
          - /queue/pong      

development:
  <<: *defaults

test:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
